export const projectsData = [
  {
    id: 1,
    title: "Car Rental Website",
    description: "A full-stack car rental platform built with React, Hono, and Drizzle.",
    category: "frontend",
    liveLink: "https://car-rental-website.com",
    sourceCode: "https://github.com/yourusername/car-rental",
  },
  {
    id: 2,
    title: "E-Commerce Platform",
    description: "An online store built with React, Node.js, and MongoDB.",
    category: "frontend",
    liveLink: "https://e-commerce-platform.com",
    sourceCode: "https://github.com/yourusername/e-commerce",
  },
  {
    id: 3,
    title: "Portfolio Website",
    description: "A personal portfolio website showcasing my projects and skills.",
    category: "frontend",
    liveLink: "https://portfolio-website.com",
    sourceCode: "https://github.com/yourusername/portfolio",
  },
  {
    id: 4,
    title: "Social links profile",
    description: "This project is a personalized social link-sharing profile that allows you to showcase and share all your social media links in one place.",
    category: "api",
    liveLink: "https://pe-te-r.github.io/social_links/",
    sourceCode: "https://github.com/Pe-te-r/social_links",
  },
  {
    id: 5,
    title: "REST Countries API with color theme switcher",
    description: "This project is a JavaScript-based web application that fetches and displays data from the REST Countries API. The goal was to test and enhance my JavaScript skills by building a dynamic and interactive user interface that showcases country information such as name, population, region, capital, and more.",
    category: "javascript",
    liveLink: "https://pe-te-r.github.io/REST-Countries-Api/",
    sourceCode: "https://github.com/Pe-te-r/REST-Countries-Api",
  },
  {
    id: 6,
    title: "Contact Form",
    description: "This project focuses on building an accessible and user-friendly form with various input types and robust validation. Accessibility is a critical aspect of modern web development, and this project provided an excellent opportunity to practice creating forms that are inclusive and easy to use for all users. ",
    category: "javascript",
    liveLink: "https://pe-te-r.github.io/contact-form/",
    sourceCode: "https://github.com/Pe-te-r/contact-form",
  },
  {
    id: 7,
    title: "CSS Grid Layout",
    description: "This project showcases a responsive and dynamic Time Tracker Dashboard built using CSS Grid. The dashboard displays various time tracking categories (e.g., work, play, study) in a clean and visually appealing grid layout.",
    category: "css",
    liveLink: "https://pe-te-r.github.io/time-tracker-dashboard/",
    sourceCode: "https://github.com/Pe-te-r/time-tracker-dashboard",
  },
  {
    id: 8,
    title: "JavaScript Game",
    description: "A simple game built with pure JavaScript.",
    category: "javascript",
    liveLink: "https://javascript-game.com",
    sourceCode: "https://github.com/yourusername/javascript-game",
  },
  {
    id: 9,
    title: "FastAPI Todo App",
    description: "A todo app built with FastAPI and React.",
    category: "api",
    liveLink: "https://fastapi-todo-app.com",
    sourceCode: "https://github.com/yourusername/fastapi-todo-app",
  },
  {
    id: 10,
    title: "Vue Dashboard",
    description: "A dashboard built with Vue.js and Tailwind CSS.",
    category: "frontend",
    liveLink: "https://vue-dashboard.com",
    sourceCode: "https://github.com/yourusername/vue-dashboard",
  },
];
